---
version: "2.1"
volumes:
  ubuntu-sshd:

services:
  ubuntu-sshd:
    build:
      context: ./ubuntu-sshd
      dockerfile: Dockerfile.template     
    container_name: ubuntu-sshd  
    ports:
      - "2222:22"
    labels:
      - io.balena.features.dbus=1
      - io.balena.features.balena-socket=1
      - io.balena.features.balena-api=1
      - io.balena.features.supervisor-api=1
    volumes:
      - ubuntu-sshd:/home